//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.ReservePartsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CheckOutOfStockNationalAvailabilityRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.OrderingRequest))]
    public partial class UserRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.UserInformation UserRequestInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.UserInformation UserRequestInfo {
            get {
                return this.UserRequestInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.UserRequestInfoField, value) != true)) {
                    this.UserRequestInfoField = value;
                    this.RaisePropertyChanged("UserRequestInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInformation", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class UserInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.AccountNumberBusinessType BusinessTypeForAccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        private System.Guid VerificationCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.AccountNumberBusinessType BusinessTypeForAccountNumber {
            get {
                return this.BusinessTypeForAccountNumberField;
            }
            set {
                if ((this.BusinessTypeForAccountNumberField.Equals(value) != true)) {
                    this.BusinessTypeForAccountNumberField = value;
                    this.RaisePropertyChanged("BusinessTypeForAccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((this.VerificationCodeField.Equals(value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckDropShipAvailabilityRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class CheckDropShipAvailabilityRequest : ProductClient.ServiceReference1.UserRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.PartWithQuantityRequest[] PartsWithQuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.PartWithQuantityRequest[] PartsWithQuantity {
            get {
                return this.PartsWithQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsWithQuantityField, value) != true)) {
                    this.PartsWithQuantityField = value;
                    this.RaisePropertyChanged("PartsWithQuantity");
                }
            }
        }

        internal bool getExtensionData()
        {
            throw new NotImplementedException();
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservePartsRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class ReservePartsRequest : ProductClient.ServiceReference1.UserRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PartsListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PartsList {
            get {
                return this.PartsListField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsListField, value) != true)) {
                    this.PartsListField = value;
                    this.RaisePropertyChanged("PartsList");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CheckOutOfStockNationalAvailabilityRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class CheckOutOfStockNationalAvailabilityRequest : ProductClient.ServiceReference1.UserRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.PartWithQuantityRequest[] PartsWithQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.PartWithQuantityRequest[] PartsWithQuantity {
            get {
                return this.PartsWithQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsWithQuantityField, value) != true)) {
                    this.PartsWithQuantityField = value;
                    this.RaisePropertyChanged("PartsWithQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderingRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class OrderingRequest : ProductClient.ServiceReference1.UserRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMPurchaseOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OrderCopyMethodType CopyMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FreightChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.KeyTrackOrderInfo KeyTrackInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> LiftgateRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OrderPartType LineItemTypesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OrderLineItem[] LineItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RepairOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ResidentialDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.SalvagePaymentInformation SalvagePaymentInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalvagePurchaseOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SaturdayDeliveryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipFromWarehouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OrderShipToAddress ShipToAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SignatureRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialInstructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WrittenByField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMPurchaseOrderNumber {
            get {
                return this.AMPurchaseOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AMPurchaseOrderNumberField, value) != true)) {
                    this.AMPurchaseOrderNumberField = value;
                    this.RaisePropertyChanged("AMPurchaseOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactName {
            get {
                return this.ContactNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactNameField, value) != true)) {
                    this.ContactNameField = value;
                    this.RaisePropertyChanged("ContactName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OrderCopyMethodType CopyMethod {
            get {
                return this.CopyMethodField;
            }
            set {
                if ((this.CopyMethodField.Equals(value) != true)) {
                    this.CopyMethodField = value;
                    this.RaisePropertyChanged("CopyMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaxNumber {
            get {
                return this.FaxNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxNumberField, value) != true)) {
                    this.FaxNumberField = value;
                    this.RaisePropertyChanged("FaxNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FreightCharges {
            get {
                return this.FreightChargesField;
            }
            set {
                if ((this.FreightChargesField.Equals(value) != true)) {
                    this.FreightChargesField = value;
                    this.RaisePropertyChanged("FreightCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.KeyTrackOrderInfo KeyTrackInfo {
            get {
                return this.KeyTrackInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyTrackInfoField, value) != true)) {
                    this.KeyTrackInfoField = value;
                    this.RaisePropertyChanged("KeyTrackInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> LiftgateRequired {
            get {
                return this.LiftgateRequiredField;
            }
            set {
                if ((this.LiftgateRequiredField.Equals(value) != true)) {
                    this.LiftgateRequiredField = value;
                    this.RaisePropertyChanged("LiftgateRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OrderPartType LineItemTypes {
            get {
                return this.LineItemTypesField;
            }
            set {
                if ((this.LineItemTypesField.Equals(value) != true)) {
                    this.LineItemTypesField = value;
                    this.RaisePropertyChanged("LineItemTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OrderLineItem[] LineItems {
            get {
                return this.LineItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.LineItemsField, value) != true)) {
                    this.LineItemsField = value;
                    this.RaisePropertyChanged("LineItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RepairOrderNumber {
            get {
                return this.RepairOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RepairOrderNumberField, value) != true)) {
                    this.RepairOrderNumberField = value;
                    this.RaisePropertyChanged("RepairOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ResidentialDelivery {
            get {
                return this.ResidentialDeliveryField;
            }
            set {
                if ((this.ResidentialDeliveryField.Equals(value) != true)) {
                    this.ResidentialDeliveryField = value;
                    this.RaisePropertyChanged("ResidentialDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.SalvagePaymentInformation SalvagePaymentInformation {
            get {
                return this.SalvagePaymentInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.SalvagePaymentInformationField, value) != true)) {
                    this.SalvagePaymentInformationField = value;
                    this.RaisePropertyChanged("SalvagePaymentInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalvagePurchaseOrderNumber {
            get {
                return this.SalvagePurchaseOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SalvagePurchaseOrderNumberField, value) != true)) {
                    this.SalvagePurchaseOrderNumberField = value;
                    this.RaisePropertyChanged("SalvagePurchaseOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SaturdayDelivery {
            get {
                return this.SaturdayDeliveryField;
            }
            set {
                if ((this.SaturdayDeliveryField.Equals(value) != true)) {
                    this.SaturdayDeliveryField = value;
                    this.RaisePropertyChanged("SaturdayDelivery");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipFromWarehouse {
            get {
                return this.ShipFromWarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipFromWarehouseField, value) != true)) {
                    this.ShipFromWarehouseField = value;
                    this.RaisePropertyChanged("ShipFromWarehouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OrderShipToAddress ShipToAddress {
            get {
                return this.ShipToAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToAddressField, value) != true)) {
                    this.ShipToAddressField = value;
                    this.RaisePropertyChanged("ShipToAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SignatureRequired {
            get {
                return this.SignatureRequiredField;
            }
            set {
                if ((this.SignatureRequiredField.Equals(value) != true)) {
                    this.SignatureRequiredField = value;
                    this.RaisePropertyChanged("SignatureRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialInstructions {
            get {
                return this.SpecialInstructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialInstructionsField, value) != true)) {
                    this.SpecialInstructionsField = value;
                    this.RaisePropertyChanged("SpecialInstructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WrittenBy {
            get {
                return this.WrittenByField;
            }
            set {
                if ((object.ReferenceEquals(this.WrittenByField, value) != true)) {
                    this.WrittenByField = value;
                    this.RaisePropertyChanged("WrittenBy");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyTrackOrderInfo", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class KeyTrackOrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InsuranceCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyTrackRepairOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VINNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceCompanyName {
            get {
                return this.InsuranceCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InsuranceCompanyNameField, value) != true)) {
                    this.InsuranceCompanyNameField = value;
                    this.RaisePropertyChanged("InsuranceCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeyTrackRepairOrderNumber {
            get {
                return this.KeyTrackRepairOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyTrackRepairOrderNumberField, value) != true)) {
                    this.KeyTrackRepairOrderNumberField = value;
                    this.RaisePropertyChanged("KeyTrackRepairOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VINNumber {
            get {
                return this.VINNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VINNumberField, value) != true)) {
                    this.VINNumberField = value;
                    this.RaisePropertyChanged("VINNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalvagePaymentInformation", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class SalvagePaymentInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardType {
            get {
                return this.CardTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CardTypeField, value) != true)) {
                    this.CardTypeField = value;
                    this.RaisePropertyChanged("CardType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckNumber {
            get {
                return this.CheckNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckNumberField, value) != true)) {
                    this.CheckNumberField = value;
                    this.RaisePropertyChanged("CheckNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method {
            get {
                return this.MethodField;
            }
            set {
                if ((object.ReferenceEquals(this.MethodField, value) != true)) {
                    this.MethodField = value;
                    this.RaisePropertyChanged("Method");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderShipToAddress", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class OrderShipToAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.ShippingAddressType ShipToCodeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipToNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipViaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToCode {
            get {
                return this.ShipToCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToCodeField, value) != true)) {
                    this.ShipToCodeField = value;
                    this.RaisePropertyChanged("ShipToCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.ShippingAddressType ShipToCodeType {
            get {
                return this.ShipToCodeTypeField;
            }
            set {
                if ((this.ShipToCodeTypeField.Equals(value) != true)) {
                    this.ShipToCodeTypeField = value;
                    this.RaisePropertyChanged("ShipToCodeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipToName {
            get {
                return this.ShipToNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipToNameField, value) != true)) {
                    this.ShipToNameField = value;
                    this.RaisePropertyChanged("ShipToName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipVia {
            get {
                return this.ShipViaField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipViaField, value) != true)) {
                    this.ShipViaField = value;
                    this.RaisePropertyChanged("ShipVia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateProvince {
            get {
                return this.StateProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.StateProvinceField, value) != true)) {
                    this.StateProvinceField = value;
                    this.RaisePropertyChanged("StateProvince");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderCopyMethodType", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    public enum OrderCopyMethodType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fax = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderPartType", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    public enum OrderPartType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aftermarket = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Salvage = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Both = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderLineItem", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class OrderLineItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentForPartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentForPickTicketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CustomerCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FreightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LineCommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitOfMeasureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool UsedPartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentForPart {
            get {
                return this.CommentForPartField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentForPartField, value) != true)) {
                    this.CommentForPartField = value;
                    this.RaisePropertyChanged("CommentForPart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommentForPickTicket {
            get {
                return this.CommentForPickTicketField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentForPickTicketField, value) != true)) {
                    this.CommentForPickTicketField = value;
                    this.RaisePropertyChanged("CommentForPickTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CustomerCost {
            get {
                return this.CustomerCostField;
            }
            set {
                if ((this.CustomerCostField.Equals(value) != true)) {
                    this.CustomerCostField = value;
                    this.RaisePropertyChanged("CustomerCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Freight {
            get {
                return this.FreightField;
            }
            set {
                if ((this.FreightField.Equals(value) != true)) {
                    this.FreightField = value;
                    this.RaisePropertyChanged("Freight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LineComment {
            get {
                return this.LineCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.LineCommentField, value) != true)) {
                    this.LineCommentField = value;
                    this.RaisePropertyChanged("LineComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber {
            get {
                return this.PartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNumberField, value) != true)) {
                    this.PartNumberField = value;
                    this.RaisePropertyChanged("PartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnitOfMeasure {
            get {
                return this.UnitOfMeasureField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitOfMeasureField, value) != true)) {
                    this.UnitOfMeasureField = value;
                    this.RaisePropertyChanged("UnitOfMeasure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UsedPart {
            get {
                return this.UsedPartField;
            }
            set {
                if ((this.UsedPartField.Equals(value) != true)) {
                    this.UsedPartField = value;
                    this.RaisePropertyChanged("UsedPart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountNumberBusinessType", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    public enum AccountNumberBusinessType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aftermarket = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Salvage = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartWithQuantityRequest", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.PartWithQuantityResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.OutOfStockNationalAvailabilityResult))]
    public partial class PartWithQuantityRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber {
            get {
                return this.PartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNumberField, value) != true)) {
                    this.PartNumberField = value;
                    this.RaisePropertyChanged("PartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartWithQuantityResult", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.OutOfStockNationalAvailabilityResult))]
    public partial class PartWithQuantityResult : ProductClient.ServiceReference1.PartWithQuantityRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutOfStockNationalAvailabilityResult", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class OutOfStockNationalAvailabilityResult : ProductClient.ServiceReference1.PartWithQuantityResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingAddressType", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    public enum ShippingAddressType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Default = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manual = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Prelude = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponse", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CallResponseOfPartsWithQuantityResultSet4MCb5AyH))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ProductClient.ServiceReference1.CallResponseOfOrderingResponse4MCb5AyH))]
    public partial class CallResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful {
            get {
                return this.IsSuccessfulField;
            }
            set {
                if ((this.IsSuccessfulField.Equals(value) != true)) {
                    this.IsSuccessfulField = value;
                    this.RaisePropertyChanged("IsSuccessful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH : ProductClient.ServiceReference1.CallResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.PartWithQuantityResult[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.PartWithQuantityResult[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponseOfPartsWithQuantityResultSet4MCb5AyH", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class CallResponseOfPartsWithQuantityResultSet4MCb5AyH : ProductClient.ServiceReference1.CallResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.PartsWithQuantityResultSet ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.PartsWithQuantityResultSet Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH : ProductClient.ServiceReference1.CallResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OutOfStockNationalAvailabilityResult[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OutOfStockNationalAvailabilityResult[] Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallResponseOfOrderingResponse4MCb5AyH", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Entities")]
    [System.SerializableAttribute()]
    public partial class CallResponseOfOrderingResponse4MCb5AyH : ProductClient.ServiceReference1.CallResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.OrderingResponse ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.OrderingResponse Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderingResponse", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class OrderingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AftermarketOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalvageOrderNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AftermarketOrderNumber {
            get {
                return this.AftermarketOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AftermarketOrderNumberField, value) != true)) {
                    this.AftermarketOrderNumberField = value;
                    this.RaisePropertyChanged("AftermarketOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalvageOrderNumber {
            get {
                return this.SalvageOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SalvageOrderNumberField, value) != true)) {
                    this.SalvageOrderNumberField = value;
                    this.RaisePropertyChanged("SalvageOrderNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartsWithQuantityResultSet", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class PartsWithQuantityResultSet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FreightRulesFoundField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProductClient.ServiceReference1.PartWithFreight[] PartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalFreightChargeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FreightRulesFound {
            get {
                return this.FreightRulesFoundField;
            }
            set {
                if ((this.FreightRulesFoundField.Equals(value) != true)) {
                    this.FreightRulesFoundField = value;
                    this.RaisePropertyChanged("FreightRulesFound");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProductClient.ServiceReference1.PartWithFreight[] Parts {
            get {
                return this.PartsField;
            }
            set {
                if ((object.ReferenceEquals(this.PartsField, value) != true)) {
                    this.PartsField = value;
                    this.RaisePropertyChanged("Parts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalFreightCharge {
            get {
                return this.TotalFreightChargeField;
            }
            set {
                if ((this.TotalFreightChargeField.Equals(value) != true)) {
                    this.TotalFreightChargeField = value;
                    this.RaisePropertyChanged("TotalFreightCharge");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartWithFreight", Namespace="http://schemas.datacontract.org/2004/07/LKQIntegrationService.Core.Ordering.Entit" +
        "ies")]
    [System.SerializableAttribute()]
    public partial class PartWithFreight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartNumber {
            get {
                return this.PartNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartNumberField, value) != true)) {
                    this.PartNumberField = value;
                    this.RaisePropertyChanged("PartNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Ordering.svc", Namespace="LKQCorp.LKQIntegrationService", ConfigurationName="ServiceReference1.Orderingsvc")]
    public interface Orderingsvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CreateOrder", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CreateOrderResponse")]
        ProductClient.ServiceReference1.CallResponseOfOrderingResponse4MCb5AyH CreateOrder(ProductClient.ServiceReference1.OrderingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CreateOrder", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CreateOrderResponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfOrderingResponse4MCb5AyH> CreateOrderAsync(ProductClient.ServiceReference1.OrderingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailability", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityResponse")]
        ProductClient.ServiceReference1.CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH CheckDropShipAvailability(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailability", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityResponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH> CheckDropShipAvailabilityAsync(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/ReserveParts", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/ReservePartsResponse")]
        ProductClient.ServiceReference1.CallResponse ReserveParts(ProductClient.ServiceReference1.ReservePartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/ReserveParts", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/ReservePartsResponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponse> ReservePartsAsync(ProductClient.ServiceReference1.ReservePartsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityWithFreight", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityWithFreightRe" +
            "sponse")]
        ProductClient.ServiceReference1.CallResponseOfPartsWithQuantityResultSet4MCb5AyH CheckDropShipAvailabilityWithFreight(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityWithFreight", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckDropShipAvailabilityWithFreightRe" +
            "sponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfPartsWithQuantityResultSet4MCb5AyH> CheckDropShipAvailabilityWithFreightAsync(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckOutOfStockNationalAvailability", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckOutOfStockNationalAvailabilityRes" +
            "ponse")]
        ProductClient.ServiceReference1.CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH CheckOutOfStockNationalAvailability(ProductClient.ServiceReference1.CheckOutOfStockNationalAvailabilityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LKQCorp.LKQIntegrationService/Ordering.svc/CheckOutOfStockNationalAvailability", ReplyAction="LKQCorp.LKQIntegrationService/Ordering.svc/CheckOutOfStockNationalAvailabilityRes" +
            "ponse")]
        System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH> CheckOutOfStockNationalAvailabilityAsync(ProductClient.ServiceReference1.CheckOutOfStockNationalAvailabilityRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderingsvcChannel : ProductClient.ServiceReference1.Orderingsvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderingsvcClient : System.ServiceModel.ClientBase<ProductClient.ServiceReference1.Orderingsvc>, ProductClient.ServiceReference1.Orderingsvc {
        
        public OrderingsvcClient() {
        }
        
        public OrderingsvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderingsvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderingsvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderingsvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProductClient.ServiceReference1.CallResponseOfOrderingResponse4MCb5AyH CreateOrder(ProductClient.ServiceReference1.OrderingRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfOrderingResponse4MCb5AyH> CreateOrderAsync(ProductClient.ServiceReference1.OrderingRequest request) {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public ProductClient.ServiceReference1.CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH CheckDropShipAvailability(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request) {
            return base.Channel.CheckDropShipAvailability(request);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfArrayOfPartWithQuantityResult4MCb5AyH> CheckDropShipAvailabilityAsync(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request) {
            return base.Channel.CheckDropShipAvailabilityAsync(request);
        }
        
        public ProductClient.ServiceReference1.CallResponse ReserveParts(ProductClient.ServiceReference1.ReservePartsRequest request) {
            return base.Channel.ReserveParts(request);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponse> ReservePartsAsync(ProductClient.ServiceReference1.ReservePartsRequest request) {
            return base.Channel.ReservePartsAsync(request);
        }
        
        public ProductClient.ServiceReference1.CallResponseOfPartsWithQuantityResultSet4MCb5AyH CheckDropShipAvailabilityWithFreight(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request) {
            return base.Channel.CheckDropShipAvailabilityWithFreight(request);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfPartsWithQuantityResultSet4MCb5AyH> CheckDropShipAvailabilityWithFreightAsync(ProductClient.ServiceReference1.CheckDropShipAvailabilityRequest request) {
            return base.Channel.CheckDropShipAvailabilityWithFreightAsync(request);
        }
        
        public ProductClient.ServiceReference1.CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH CheckOutOfStockNationalAvailability(ProductClient.ServiceReference1.CheckOutOfStockNationalAvailabilityRequest request) {
            return base.Channel.CheckOutOfStockNationalAvailability(request);
        }
        
        public System.Threading.Tasks.Task<ProductClient.ServiceReference1.CallResponseOfArrayOfOutOfStockNationalAvailabilityResult4MCb5AyH> CheckOutOfStockNationalAvailabilityAsync(ProductClient.ServiceReference1.CheckOutOfStockNationalAvailabilityRequest request) {
            return base.Channel.CheckOutOfStockNationalAvailabilityAsync(request);
        }

        internal void CheckDropShipAvailability(PartWithQuantityRequest partWithQuantityReq)
        {
            throw new NotImplementedException();
        }

        internal void InnerChannel()
        {
            throw new NotImplementedException();
        }
    }
}
